export const metadata = {
  title: "Portfolio - Checkout page",
  description: "Portfolio Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <section className="">{children}</section>;
}
