import "../../styles/Collections.css";

export const metadata = {
  title: "Portfolio - collections",
  description: "Portfolio Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <section className="products-container">{children}</section>;
}
