import "../styles/globals.css";
import Footer from "./Footer";
import Header from "./Header";
import { ReduxProviders } from "../redux/provider";
import ThemeProviders from "./ThemeProviders";
import React from "react";

export const metadata = {
  title: "Portfolio - Main page",
  description: "Portfolio Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100 dark:bg-zinc-800 transition-all duration-700">
        <ThemeProviders>
          <ReduxProviders>
            <Header />
            <div>{children}</div>
            <Footer />
          </ReduxProviders>
        </ThemeProviders>
      </body>
    </html>
  );
}
