import "../../styles/PortfolioSlider.css";

export const metadata = {
  title: "Portfolio - CV",
  description: "Portfolio Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
