import "../../styles/Products.css";

export const metadata = {
  title: "Portfolio - Products page",
  description: "Portfolio Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <section className="products-container">{children}</section>;
}
