import "@/styles/SignUpPage.css";
import PageWrapper from "@/app/pageWrapper";

export const metadata = {
  title: "Portfolio - Sign-up",
  description: "Portfolio Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section>
      <PageWrapper>
        <div>{children}</div>
      </PageWrapper>
    </section>
  );
}
